name: GCP Create Storage Lab

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Create Cloud Storage Bucket
        run: |
          # Criamos um nome único usando o ID do Run do GitHub para evitar erro de nome já existente
          BUCKET_NAME="bucket-lab-jairo-${{ github.run_id }}"
          echo "Criando bucket: $BUCKET_NAME"
          gcloud storage buckets create gs://$BUCKET_NAME --location=us-central1